export const banderas: Record<string, string> = {
  "España": "🇪🇸",
  "Francia": "🇫🇷",
  "Alemania": "🇩🇪",
  "Italia": "🇮🇹",
  "Portugal": "🇵🇹",
  "Inglaterra": "🇬🇧",
  "Países Bajos": "🇳🇱",
  "Bélgica": "🇧🇪",
  "Croacia": "🇭🇷",
  "Suiza": "🇨🇭",

  "Argentina": "🇦🇷",
  "Brasil": "🇧🇷",
  "Uruguay": "🇺🇾",
  "Colombia": "🇨🇴",
  "Ecuador": "🇪🇨",

  "México": "🇲🇽",
  "Estados Unidos": "🇺🇸",
  "Canadá": "🇨🇦",

  "Marruecos": "🇲🇦",
  "Senegal": "🇸🇳",
  "Egipto": "🇪🇬",
  "Ghana": "🇬🇭",

  "Japón": "🇯🇵",
  "Corea del Sur": "🇰🇷",
  "Australia": "🇦🇺",
  "Irán": "🇮🇷",
  "Arabia Saudí": "🇸🇦",

  "Sudáfrica": "🇿🇦",
  "Chequia": "🇨🇿",
  "Austria": "🇦🇹",
  "Argelia": "🇩🇿",
  "Irak": "🇮🇶",
  "Noruega": "🇳🇴",
  "Cabo Verde": "🇨🇻",
  "Jordania": "🇯🇴",

  "Turquía": "🇹🇷",
  "Costa de Marfil": "🇨🇮",
  "Escocia": "🇬🇧",
  "Bosnia y Herzegovina": "🇧🇦",
  "Curazao": "🇨🇼",
  "Uzbekistán": "🇺🇿",
  "RD Congo": "🇨🇩",
  "Haití": "🇭🇹",
  "Suecia": "🇸🇪",
  "Nueva Zelanda": "🇳🇿",
"Túnez": "🇹🇳",
"Panamá": "🇵🇦",
"Qatar": "🇶🇦",
"Paraguay": "🇵🇾",
  

  
};