export const banderas: Record<string, string> = {
  "España": "es",
  "Francia": "fr",
  "Alemania": "de",
  "Italia": "it",
  "Portugal": "pt",
  "Inglaterra": "gb",
  "Países Bajos": "nl",
  "Bélgica": "be",
  "Croacia": "hr",
  "Serbia": "rs",
  "Suiza": "ch",
  "Dinamarca": "dk",
  "Polonia": "pl",
  "Ucrania": "ua",

  "Argentina": "ar",
  "Brasil": "br",
  "Uruguay": "uy",
  "Colombia": "co",
  "Ecuador": "ec",
  "Chile": "cl",
  "Paraguay": "py",
  "Perú": "pe",

  "México": "mx",
  "Estados Unidos": "us",
  "Canadá": "ca",
  "Costa Rica": "cr",
  "Panamá": "pa",

  "Marruecos": "ma",
  "Senegal": "sn",
  "Túnez": "tn",
  "Egipto": "eg",
  "Camerún": "cm",
  "Ghana": "gh",
  "Nigeria": "ng",

  "Japón": "jp",
  "Corea del Sur": "kr",
  "Australia": "au",
  "Irán": "ir",
  "Arabia Saudí": "sa",
  "Catar": "qa",

  "Nueva Zelanda": "nz",
};